export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_FOODS_PENDING = "REQUEST_FOODS_PENDING";
export const REQUEST_FOODS_SUCCESS = "REQUEST_FOODS_SUCCESS";
export const REQUEST_FOODS_FAILED = "REQUEST_FOODS_FAILED";
